// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4yskWUR8A9AJQmOFnNORVm75YCtv8BGs',
    appId: '1:83875234510:web:00c78008e6bebcdd8b869f',
    messagingSenderId: '83875234510',
    projectId: 'fir-money-20c76',
    authDomain: 'fir-money-20c76.firebaseapp.com',
    storageBucket: 'fir-money-20c76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jvuCFv2eihAgqg6lwHTpYrpzDXtU_Qo',
    appId: '1:83875234510:android:9424c2e8a6454d468b869f',
    messagingSenderId: '83875234510',
    projectId: 'fir-money-20c76',
    storageBucket: 'fir-money-20c76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzqrcypnTDa-vUWDDlbWyNgyYxl9xoyE',
    appId: '1:83875234510:ios:8ab6015ad4449e598b869f',
    messagingSenderId: '83875234510',
    projectId: 'fir-money-20c76',
    storageBucket: 'fir-money-20c76.firebasestorage.app',
    iosBundleId: 'com.example.fluttermoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGzqrcypnTDa-vUWDDlbWyNgyYxl9xoyE',
    appId: '1:83875234510:ios:8ab6015ad4449e598b869f',
    messagingSenderId: '83875234510',
    projectId: 'fir-money-20c76',
    storageBucket: 'fir-money-20c76.firebasestorage.app',
    iosBundleId: 'com.example.fluttermoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4yskWUR8A9AJQmOFnNORVm75YCtv8BGs',
    appId: '1:83875234510:web:99af247048cd87768b869f',
    messagingSenderId: '83875234510',
    projectId: 'fir-money-20c76',
    authDomain: 'fir-money-20c76.firebaseapp.com',
    storageBucket: 'fir-money-20c76.firebasestorage.app',
  );
}
