import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:fluttermoney/screens/expense_detail_screen.dart';
import 'package:fluttermoney/screens/home_screen.dart';
import 'package:fluttermoney/screens/select_alokasi_screen.dart';
import 'package:fluttermoney/screens/select_subcategory_screen.dart';
import 'package:fluttermoney/services/cache_service.dart';
import 'firebase_options.dart'; // The file generated by CLI
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:go_router/go_router.dart';

Future<void> initSession2() async {
  await FirebaseFirestore.instance.collection('session').add({
    'message': 'he2h',
    'time': DateTime.now(),
  });
}

void main() async {
  // 1. Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase using the generated options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  await CacheService().loadAllData();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final GoRouter _router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        name: 'home',
        builder: (context, state) => const HomeScreen(),
      ),
      // First screen - Select Alokasi
      GoRoute(
        path: '/select-alokasi',
        name: 'select-alokasi',
        builder: (context, state) => const SelectAlokasiScreen(),
      ),
      // Second screen - Select SubCategory (only for normal categories)
      GoRoute(
        path: '/select-subcategory',
        name: 'select-subcategory',
        builder: (context, state) {
          final alokasi = state.extra as String;
          return SelectSubCategoryScreen(alokasi: alokasi);
        },
      ),
      // Third screen - Form with amount & description
      GoRoute(
        path: '/expense-detail',
        name: 'expense-detail',
        builder: (context, state) {
          final args = state.extra as Map<String, dynamic>;
          return ExpenseDetailScreen(
            alokasi: args['alokasi'],
            subCategory: args['subCategory'],
          );
        },
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(title: 'Expense Tracker', routerConfig: _router);
  }
}
